### ISSUE TITLE
Cannot find example of phenotype file

### ISSUE THREAD

**Issue by MrLocuace** [Atkinson-Lab/Tractor#11]
Hello,
I am unable to find the exact format of the Phe.txt file described here:

https://github.com/Atkinson-Lab/Tractor-tutorial/blob/main/Local.md

python RunTractor.py --hapdose ADMIX_COHORT/ASW.phased --phe PHENO/Phe.txt --method linear --out SumStats.tsv

Please help
Thank you

**Comment by JasonTan-code** [comment]
`Phe.txt` is a tsv file with at least two columns (with header). The first column is IID, the second column is y (phenotype), and of course you can include more columns (need to be encoded as numbers) as covariates. 

I will add more descriptions to the tutorial page, and thanks for your feedback!

**Comment by MrLocuace** [comment]
Thank you !
