### ISSUE TITLE
NaN output

### ISSUE THREAD

**Issue by spaul-genetics** [Atkinson-Lab/Tractor#13]
I am applying the pipeline on imputed data (chr 21) of 934 cases and 946 controls. The output I got contains all nan. Is it possibly due to the small sample size?

**Comment by JasonTan-code** [comment]
This could happen if one of your dosage file contains all 0s, and if that happens, the program can’t fit a linear/logistic regression. Have you checked the global proportions of admixture? 
If this is the problem, you may need to consider reducing the number of local ancestries call (for example, from 3-way LAI to 2-way LAI).

**Comment by nirav572** [comment]
Closing the issue due to long inactivity.

**Comment by nirav572** [comment]
Closing this issue due to prolonged inactivity.
