### ISSUE TITLE
How were the painted karyograms made?

### ISSUE THREAD

**Issue by Naughtoncolin** [Atkinson-Lab/Tractor#14]

**Comment by guidebortoli** [comment]
Hi, I am interested (if possible and available), for the modified script to Alicia's Karyogram plot from RFMix v1 output to RFMix v2 output...
Unfortunately I can;'t find anywhere a way to generate karyograms of LAI from RFMix v2 output...

Thanks

**Comment by eatkinson** [comment]
Hi! I made those painted karyograms on another branch from Alicia's original pipeline - see especially this conversion script - https://github.com/eatkinson/ancestry_pipeline/blob/master/RFmixv2_plotconversion.txt
