### ISSUE TITLE
Error message in the tutorial

### ISSUE THREAD

**Issue by ZikunY** [Atkinson-Lab/Tractor#15]
Hi,

I was following the tutorial with the example dataset, and I got the error message when I was running the following code,

python Tractor/ExtractTracts.py
--msp ADMIX_COHORT/ASW.deconvoluted
--vcf ADMIX_COHORT/ASW.phased
--zipped
--num-ancs 2

The error message is

File "Tractor/ExtractTracts.py", line 24
def extract_tracts(msp: str, vcf_prefix: str, zipped: bool, zip_output:bool, output_path:str, num_ancs: int = 2):
^
SyntaxError: invalid syntax

Could you let me know where I got wrong? Thanks!

**Comment by mike-w-wilson** [comment]
Hi @ZikunY,

This looks like an error message from python2. Can you try to running the script with python3?

**Comment by ZikunY** [comment]
Thanks, Mike! It works.
