### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by ZikunY** [Atkinson-Lab/Tractor#18]
Hi, 

I had this error while running the function of extracting the tracts, ExtractTracts.py. The input vcf file is not phased, though RFMix still gave reasonable results. So my question is that does Tractor here require phased vcf file to run the function? Thanks a lot for the help!

INFO (__main__ 42): Creating output files for 2 ancestries
INFO (__main__ 48): Opening input and output files for reading and writing
Traceback (most recent call last):
  File "/Tractor/ExtractTracts.py", line 184, in <module>
    extract_tracts(**vars(args))
  File "/Tractor/ExtractTracts.py", line 126, in extract_tracts
    geno_b = str(geno[1])
                 ~~~~^^^
IndexError: list index out of range

**Comment by mike-w-wilson** [comment]
Hi @ZikunY, Tractor does require a phased VCF file as it expects the GT delimiter to be "|" instead of "/". Without a phased GT, the code cannot split the GT field into appropriate ancestries.

**Comment by ZikunY** [comment]
Yes, it is exactly the problem. I phased the vcf by Shapeit, and the error was no more, thanks for the help!
