### ISSUE TITLE
Related samples

### ISSUE THREAD

**Issue by Wanying-Zhu** [Atkinson-Lab/Tractor#19]
Hi,

I would like to apply Tractor to a dataset with high relatedness, but it looks like Tractor does not take in GRM.
Besides using an unrelated subset, do you have other suggestions?

Thanks,
Wanying

**Comment by JasonTan-code** [comment]
I am currently working on a project Tractor-Mix, which will take GRM into account. It hopefully will be available to cite in a few months. But at the moment, the best practice is to remove some relatives.

**Comment by nirav572** [comment]
Another project will allow for inclusion of relatedness.
