### ISSUE TITLE
Dependency on RFMIX Output Format

### ISSUE THREAD

**Issue by kscott-1** [Atkinson-Lab/Tractor#21]
HI! I have been looking at Tractor for usage in a new project. The program for Local Ancestry that we are likely to use in this project is [Flare](https://github.com/browning-lab/flare). This program outputs predicted ancestry in VCF format with AN1 & AN2 as fields. The program predicts ancestry only for the variants at which the input file has GT data.

Given that Tractor seems to require input in RFMIX format, there are some concerns with attempting to use the program. Is there anything in development to support other LA programs such as Flare?

Any help would be appreciated, thanks!

**Comment by nirav572** [comment]
Hi @kscott-1, Thank you for your interest in Tractor.

We've just updated our scripts, ensuring compatibility with FLARE in the extracting tracts script. Feel free to explore the latest version and reach out if you have any questions or feedback. Kindly note that the Tractor code has also been modified, so please pull the latest changes before your runs.

**Comment by kscott-1** [comment]
Awesome, thanks for your work! I will be testing it out.
