### ISSUE TITLE
`extract_tracks.py`: NameError: name 'output_files' is not defined

### ISSUE THREAD

**Issue by biona001** [Atkinson-Lab/Tractor#26]
Hi, 

I was trying to run the `extract_tracks.py` script, but it threw an error

```
$ python3 /u/home/b/biona001/Tractor/scripts/extract_tracts.py \
    --vcf /u/home/b/biona001/project-loes/ForBen_genotypes_subset/LAI/vcf_phased/chr22.vcf.gz \
    --msp /u/home/b/biona001/project-loes/ForBen_genotypes_subset/LAI/output/chr22.msp.tsv \
    --num-ancs 3 \
    --output-dir /u/home/b/biona001/project-loes/ForBen_genotypes_subset/LAI/tracks

INFO (__main__ 90): # VCF File                    : /u/home/b/biona001/project-loes/ForBen_genotypes_subset/LAI/vcf_phased/chr22.vcf.gz
INFO (__main__ 91): # Prefix of output file names : chr22
INFO (__main__ 92): # VCF File is compressed?     : True
INFO (__main__ 93): # Number of Ancestries in VCF : 3
INFO (__main__ 94): # Output Directory            : /u/home/b/biona001/project-loes/ForBen_genotypes_subset/LAI/tracks
INFO (__main__ 100): Creating output files for 3 ancestries
Traceback (most recent call last):
  File "/u/home/b/biona001/Tractor/scripts/extract_tracts.py", line 239, in <module>
    extract_tracts(**vars(args))
  File "/u/home/b/biona001/Tractor/scripts/extract_tracts.py", line 102, in extract_tracts
    output_files[f"dos{i}"] = f"{output_path}anc{i}.dosage.txt{file_extension}"
NameError: name 'output_files' is not defined
```
Any tips/suggestions would be highly appreciated.

**Comment by biona001** [comment]
In `extract_tracts` function I tried adding the line
```
output_files = {}
```
but it led to another error
```
NameError: name 'geno_parts' is not defined
```
Then I modified the variable `geno_parts` to just `genos` and the script worked.

**Comment by samreenzafer** [comment]
I figured this error out.

`File "Tractor/scripts/extract_tracts.py", line 181, in extract_tracts
geno_a,geno_b = map(str, geno[:2])
ValueError: not enough values to unpack (expected 2, got 1)`


There were variants in the phased which had no-calls, and this was causing the trouble.
I originally had 3 cohorts, on which I did phasing separately, and then merged (bcftools merge) the phased vcf files to proceed with LAI and Tractor. While merging variants some samples which did not have variants in other 2 cohorts were given ./. genotypes. Extract_tractor could not handle such genotypes.

I then did a bcftools +missing2ref to the merged_phased vcf files, and now the subsequent tractor steps work properly.
bcftools merge --threads $threads -o $output.vcf.gz -O z cohort1.chr$i.phase.vcf.gz cohort2.chr$i.phase.vcf.gz cohort2.chr$i.phase.vcf.gz | bcftools +missing2ref -O z -o $output.missing2ref.vcf.gz   -p -m

**Comment by nirav572** [comment]
Hi @biona001, Thank you for the bug report and the recommended fix. We have implemented the necessary changes in the code, and should work once you pull the code to the most recent version.

**Comment by nirav572** [comment]
@EfraMP A quick search tells me this might have to do with data types. We are happy to look into it, but please open another  issue for this. If you can details or provide an example of files you are inputting so we can replicate on our end, that would be helpful.

@samreenzafer You are correct, extract_tracts.py does expect that there are no missing values in the VCF files.
