### ISSUE TITLE
Differences in AF between original version and v 1.1.0

### ISSUE THREAD

**Issue by nick338** [Atkinson-Lab/Tractor#27]
Hello,

I ran tractor on the same cohort using the same rfmix output and noticed that the AF for some variants differed between my original tractor output and the v1.1.0 output. Was there any difference in how AF was calculated in the new version of tractor? 
Thanks for any help you can provide.

**Comment by JasonTan-code** [comment]
Hi, do you mean the AF is different for **some** variants or for **all** variants? If possible, can you send me a few variants through my email (Taotao.Tan@bcm.edu)? You may subset a few variants in the file of anc*.hapcount.txt and anc*.dosage.txt and share them with me.

**Comment by nirav572** [comment]
Hi @nick338,

Thanks for pointing this out. There was a small error in dosage computation in the `extract_tracts.py` script that is now fixed. Please try again with the updated script.

Thank you.
