### ISSUE TITLE
Support for mixed models

### ISSUE THREAD

**Issue by la-mendicino** [Atkinson-Lab/Tractor#40]
Hi Atkinson Lab,

First off, thank you for your work on these methods!

I am curious if you have done anything on extending the run_tractor.R function to handle random effects, mainly random intercepts for something like contributing study. Thanks!

Best,

Lucas

**Comment by JasonTan-code** [comment]
Yeah, we are actually very close to the release of Tractor-Mix. We have done both simulations and empirical testing. Hopefully it will come out in the next month or two. Thanks for your interest in this method!

**Comment by la-mendicino** [comment]
Awesome, thank you! Keep up the good work!
